### ISSUE TITLE
В окне настроек список авторов отображается не полностью на некоторых экранах

### ISSUE THREAD

**Issue by k4li-0x0** [paolalenti/Book-of-recipes#11]
Возможно стоит добавить ScrollView

**Устройство**: Xiaomi Redmi 8
**Размер экрана**: 720 x 1520 pixels, 19:9 ratio (~270 ppi density)
**Шаги по воспроизведению**: 
1. открыть окно найстроек

**Comment by AliyaKad** [comment]
сделано
